# Generated by Django 4.2.29 on 2026-03-04 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TextAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField()),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("sentiment", "Sentiment Analysis"),
                            ("entities", "Entity Extraction"),
                            ("language", "Language Detection"),
                            ("translation", "Translation"),
                            ("summarization", "Text Summarization"),
                            ("classification", "Text Classification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(default=dict)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Analysis",
                "verbose_name_plural": "Text Analyses",
                "db_table": "text_analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
