# Generated by Django 4.2.29 on 2026-05-18 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecyclingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=3, max_digits=8)),
                ("price_tnd", models.DecimalField(decimal_places=3, max_digits=10)),
                ("points", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recycling_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recycling Event",
                "verbose_name_plural": "Recycling Events",
                "db_table": "recycling_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
