# Generated by Django 4.2.29 on 2026-05-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_recyclingevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclingevent",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="recyclingevent",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="recyclingevent",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recyclingevent",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recyclingevent",
            name="zone",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
