# Generated by Django 4.2.30 on 2026-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_recyclingevent_city_recyclingevent_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclingevent",
            name="waste_type",
            field=models.CharField(default="Autre", max_length=50),
        ),
    ]
