# Generated by Django 4.2.29 on 2026-03-04 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vision/images/")),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("ocr", "OCR - Text Recognition"),
                            ("labels", "Label Detection"),
                            ("faces", "Face Detection"),
                            ("objects", "Object Detection"),
                            ("landmarks", "Landmark Detection"),
                            ("logos", "Logo Detection"),
                            ("safe_search", "Safe Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Analysis",
                "verbose_name_plural": "Image Analyses",
                "db_table": "image_analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
